In [ ]:
%pip install numpy


In [ ]:
import numpy as np

# Numpy

- *NumPy stands for Numerical Python.*
* *NumPy was created in 2005 by Travis Oliphant. It is an open source project and you can use it freely.*
* *NumPy is the fundamental package for scientific computing in Python.*
* *NumPy is a Python library used for working with arrays.*
* *It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.*

## Why Numpy?

* *In Python we have lists that serve the purpose of arrays, but they are slow to process.*
* *NumPy arrays are stored at one continuous place in memory unlike lists, so processes can access and manipulate them very efficiently.*
* *This is the main reason why NumPy is faster than lists. Also it is optimized to work with latest CPU architectures.*

#### Importing Numpy

*Once NumPy is installed, import it in your applications by adding the `import` keyword:*

In [ ]:
import numpy

*Now NumPy is imported and ready to use.*

#### NumPy as np


*`NumPy` is usually imported under the `np` alias.*

*Create an alias with the `as` keyword while importing.*

*Now the NumPy package can be referred to as `np` instead of `numpy`.*

In [ ]:
import numpy as np

####  Checking NumPy Version

*The version string is stored under `__version__` attribute.*

In [ ]:
print(np.__version__)

2.0.2


#  NumPy Creating Arrays

*NumPy is used to work with arrays. The array object in NumPy is called `ndarray`.*

*We can create a NumPy `ndarray` object by using the `array()` function.*

*To create an ndarray, we can pass a list, tuple or any array-like object into the `array()` method, and it will be converted into an ndarray:*

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


#  Dimensions in Arrays

*A dimension in arrays is one level of array depth (nested arrays).*

![numpy_array_t.png](attachment:numpy_array_t.png)

### 0-D Arrays

*0-D arrays, or Scalars, are the elements in an array. Each value in an array is a 0-D array*

In [ ]:
arr = np.array(42)
print(arr)

42


###  1-D Arrays

*An array that has 0-D arrays as its elements is called uni-dimensional or 1-D array.*

*These are the most common and basic arrays.*


In [ ]:
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


###  2-D Arrays

*An array that has 1-D arrays as its elements is called a 2-D array.*

*These are often used to represent matrix or 2nd order tensors.*

In [ ]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
print(arr)

[[1 2 3]
 [4 5 6]]


###  3-D arrays

*An array that has 2-D arrays (matrices) as its elements is called 3-D array.*

In [ ]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


###  Higher Dimensional Arrays

*An array can have any number of dimensions.*

*When the array is created, you can define the number of dimensions by using the `ndmin` argument.*

In [ ]:
arr = np.array([1, 2, 3, 4], ndmin=5)
print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


##  NumPy - Data Types

*NumPy supports a much greater variety of numerical types than Python does. *

*Each built-in data type has a character code that uniquely identifies it.*

* 'b' − boolean

* 'i' − (signed) integer

* 'u' − unsigned integer

* 'f' − floating-point

* 'c' − complex-floating point

* 'm' − timedelta

* 'M' − datetime

* 'O' − (Python) objects

* 'S', 'a' − (byte-)string

* 'U' − Unicode

* 'V' − raw data (void)

#### Checking the Data Type of an Array

*The NumPy array object has a property called `dtype` that returns the data type of the array:*

In [ ]:
arr = np.array([1, 2, 3, 4])
print(arr.dtype)

int64


In [ ]:
arr = np.array(['apple', 'banana', 'cherry'])
print(arr.dtype)

<U6


##  NumPy - Array Attributes

###  1. ndarray.shape

*NumPy arrays have an attribute called `shape` that returns a tuple with each index having the number of corresponding elements. It can also be used to resize the array.*

In [ ]:
a = np.array([[1,2,3],[4,5,6]])
print(a)
print(a.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


#### a) Reshaping arrays  

*Reshaping means changing the shape of an array.*

*The shape of an array is the number of elements in each dimension.*

*By reshaping we can add or remove dimensions or change number of elements in each dimension.*

In [ ]:
a = np.array([[1,2,3],[4,5,6]])
a.shape = (3,2)
print(a)

[[1 2]
 [3 4]
 [5 6]]


### ndarray.reshape

*NumPy also provides a `reshape` function to resize an array.*

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(4, 3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


*Converting 1D array with 8 elements to a 2D array with 3 elements in each dimension (will raise an error)*

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
newarr = arr.reshape(3, 3)
print(newarr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


### 2. ndarray.ndim

*NumPy Arrays provides the `ndim` attribute that returns an integer that tells us how many dimensions the array have.*

In [ ]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


### 3. numpy.itemsize

*This array attribute returns the length of each element of array in bytes.*

In [ ]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.itemsize)
print(b.itemsize)
print(c.itemsize)
print(d.itemsize)

8
8
8
8


### 3.  ndarray.size()

*In Python, `numpy.size()` function count the number of elements along a given axis.*

In [ ]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.size)
print(b.size)
print(c.size)
print(d.size)

1
5
6
12


### 4.  ndarray.nbytes

*`ndarray.nbytes()` function return total bytes consumed by the elements of the array.*

In [ ]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.nbytes)
print(b.nbytes)
print(c.nbytes)
print(d.nbytes)

8
40
48
96


# NumPy - Array Creation Routines

*A new ndarray object can be constructed by any of the following array creation routines or using a low-level ndarray constructor.*

### numpy.empty

*It creates an uninitialized array of specified shape and dtype. It uses the following constructor −*

*`numpy.empty(shape, dtype = float, order = 'C')`*

##### The Constructor takes the following parameters:
|S.No.|Parameter|Description|
|-----|---------|-----------|
|1|Shape|Shape of an empty array in int or tuple of int|
|2|Dtype|Desired output data type.Optional|
|3|Order|'C' for C-style row-major array, 'F' for FORTAN style column-major array|

In [ ]:
x = np.empty([3,2], dtype = int)
print (x)

[[1 2]
 [3 4]
 [5 6]]


*__Note__ − The elements in an array show random values as they are not initialized.*

###  numpy.zeros

*Returns a new array of specified size, filled with zeros.*

*`numpy.zeros(shape, dtype = float, order = 'C')`*

##### The Constructor takes the following parameters:
|S.No.|Parameter|Description|
|-----|---------|-----------|
|1|Shape|Shape of an empty array in int or tuple of int|
|2|Dtype|Desired output data type.Optional|
|3|Order|'C' for C-style row-major array, 'F' for FORTAN style column-major array|

In [ ]:
x = np.zeros((5,), dtype = int)
print (x)

[0 0 0 0 0]


In [ ]:
x = np.zeros((2,2))
print (x)

[[0. 0.]
 [0. 0.]]


###  numpy.ones

*Returns a new array of specified size and type, filled with ones.*

*`numpy.ones(shape, dtype = None, order = 'C')`*

##### The Constructor takes the following parameters:
|S.No.|Parameter|Description|
|-----|---------|-----------|
|1|Shape|Shape of an empty array in int or tuple of int|
|2|Dtype|Desired output data type.Optional|
|3|Order|'C' for C-style row-major array, 'F' for FORTAN style column-major array|

In [ ]:
x = np.ones(5)
print (x)

[1. 1. 1. 1. 1.]


In [ ]:
import numpy as np
x = np.ones([2,2], dtype = int)
print (x)

[[1 1]
 [1 1]]


> *`np.empty()` is used to create empty array and the content of array is random and also depends on the state of memory. `empty()` is faster than `zeros()`. `empty()` will allocate random values if `zeros()` or `ones()` is not used before. Otherwise, it fills array with 0's or 1's based on the function used before. Allocation of values by `empty()` is completely based on the memory buffer.*

### numpy.identity
Return the identity array.
The identity array is a square array with ones on the main diagonal.

*`numpy.identity(n, dtype=None, *, like=None)`*

In [ ]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### numpy.full

*Return a new array of given shape and type, filled with fill_value.*

*`numpy.full(shape, fill_value, dtype=None, order='C', *, like=None)`*


In [ ]:
np.full((2, 2), 10)

array([[10, 10],
       [10, 10]])

### numpy.copy
*Return an array copy of the given object*

*`numpy.copy(a, order='K', subok=False)`*

In [ ]:
a = np.array([1, 'm', [2, 3, 4]], dtype=object)
b = np.copy(a)
b[2][0] = 10
print(a)

[1 'm' list([10, 3, 4])]


### numpy.eye

*Returns a 2-D array with ones on the diagonal and zeroes elsewhere*

*`numpy.eye(N, M=None, k=0, dtype=<class 'float'>, order='C', *, like=None)`*

In [ ]:
a = np.eye(3,5)
b = np.eye(3,5,k = -1,dtype = int)
print(a)
print(b)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]
[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 1 0 0 0]]


### numpy.unique

*Returns unique elements of array*

*`numpy.unique(a,return_counts = None,return_index = None,return_inverse =None,axis = None,equal_nan = True)`*

_return_index: also returns indices of the array that results in the unique array(index of first occurance of an element in array)_

_return_counts: also returns no.of times each unique item appears in array_

_return_inverse: also returns indices of unique array_

In [ ]:
n = np.array([1,2,2,2,3,3,3,3,4,4,4,5])
l = np.array([2,3,2,3,4,5,3,4,5,4,5,4,5,5,1])
print(np.unique(n))
print(np.unique(n,return_index = True))
print(np.unique(n,return_counts = True))
print(np.unique(n,return_inverse = True))
m = np.array([[1,2,3],
             [4,5,6],
             [3,2,1],
             [7,8,8],
             [7,8,8]])
print(np.unique(m))
print(np.unique(m,axis = 0))
print(np.unique(m,axis = 1))
print(np.unique(l,return_index = True))
print(np.unique(l,return_inverse = True))

[1 2 3 4 5]
(array([1, 2, 3, 4, 5]), array([ 0,  1,  4,  8, 11]))
(array([1, 2, 3, 4, 5]), array([1, 3, 4, 3, 1]))
(array([1, 2, 3, 4, 5]), array([0, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 4]))
[1 2 3 4 5 6 7 8]
[[1 2 3]
 [3 2 1]
 [4 5 6]
 [7 8 8]]
[[1 2 3]
 [4 5 6]
 [3 2 1]
 [7 8 8]
 [7 8 8]]
(array([1, 2, 3, 4, 5]), array([14,  0,  1,  4,  5]))
(array([1, 2, 3, 4, 5]), array([1, 2, 1, 2, 3, 4, 2, 3, 4, 3, 4, 3, 4, 4, 0]))


### numpy.diag

*`numpy.diag(v,k=0)`*

_Extract a diagonal or constructs a diagonal array_

*k: diagonal number*

In [ ]:
a = np.arange(1,13).reshape(3,4)
print(a)
print(np.diag(a)) #Extracting a diagonal array
print(np.diag([1,1,1,1])) #Constructing a diagonal array

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[ 1  6 11]
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


### diagflat

*`numpy.diagflat(v,k=0)`*

*Create a two-dimensional array with the flattened input as a diagonal.*

*k: diagonal number*

In [ ]:
print(np.diagflat([9,9,9]))
print(np.diagflat([9,9,9],k=1))
print(np.diagflat([9,9,9],k=-2))

[[9 0 0]
 [0 9 0]
 [0 0 9]]
[[0 9 0 0]
 [0 0 9 0]
 [0 0 0 9]
 [0 0 0 0]]
[[0 0 0 0 0]
 [0 0 0 0 0]
 [9 0 0 0 0]
 [0 9 0 0 0]
 [0 0 9 0 0]]


### numpy.flatten

*`ndarray.flatten(order='C')`*

*Return a copy of the array collapsed into one dimension.*

In [ ]:
b = np.arange(1,17).reshape(4,4)
print(b.flatten(order = 'C')) #row major
print(b.flatten(order = 'F')) #column major

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
[ 1  5  9 13  2  6 10 14  3  7 11 15  4  8 12 16]


### Random sampling (numpy.random)
*Numpy’s random number routines produce pseudo random numbers using combinations of a BitGenerator to create sequences and a Generator to use those sequences to sample from different statistical distributions.*

##### Generate a random integer from 0 to 100:
NumPy offers the `random` module to work with random numbers.

In [ ]:
from numpy import random
x = random.randint(100)
print(x)

86


##### Generate a random float from 0 to 1:
The random module's `rand()` method returns a random float between 0 and 1:

In [ ]:
from numpy import random
x = random.rand()
print(x)

0.7115907336146622


##### Generate a 1-D array containing 5 random integers from 0 to 100:
The `randint()` method takes a `size` parameter where you can specify the shape of an array.


In [ ]:
from numpy import random
x=random.randint(100, size=(5))
print(x)

[15  8 25 45 40]


##### Generate a 1-D array containing 5 random floats:
The `rand()` method also allows you to specify the shape of the array.

In [ ]:
from numpy import random
x = random.rand(5)
print(x)

[0.323236   0.71564954 0.36918711 0.04485567 0.66041004]


##### Generate Random Number From Array
The `choice()` method allows you to generate a random value based on an array of values.
The `choice()` method takes an array as a parameter and randomly returns one of the values.

In [ ]:
# Return one of the values in an array:
from numpy import random
x = random.choice([3, 5, 7, 9])
print(x)

9


##### Generate a 2-D array that consists of the values in the array parameter (3, 5, 7, and 9):
The `choice()` method also allows you to return an array of values.
Add a `size` parameter to specify the shape of the array.


In [ ]:
from numpy import random
x = random.choice([3, 5, 7, 9], size=(3, 5))
print(x)

[[9 7 5 5 7]
 [5 9 5 7 9]
 [9 9 3 3 7]]


## Numpy Arange

### numpy.arange

*This function returns an ndarray object containing evenly spaced values within a given range. The format of the function is as follows −*

*`numpy.arange(start, stop, step, dtype)`*

##### The Constructor takes the following parameters:
|S.No.|Parameter|Description|
|-----|---------|-----------|
|1|start|The start of an interval.If omitted,defaults to 0|
|2|stop|The end of an interval (not including this number)|
|3|step|Spacing between values,default is 1|
|4|dtype|Data type of resulting ndarray.If not given,data type of input is used


<div class = "alert alert-block alert-info">
            <I>The basic difference between numpy arange and python range is python range returns the range instance whereas the numpy arange returns the numpy array.</I>
        </div>

In [ ]:
x = np.arange(5)
print (x)

[0 1 2 3 4]


In [ ]:
x = np.arange(5, dtype = float)
print (x)

[0. 1. 2. 3. 4.]


In [ ]:
x = np.arange(10,20,2)
print (x)

[10 12 14 16 18]


In [ ]:
x = np.arange(0,20.6,2.3)
print (x)

[ 0.   2.3  4.6  6.9  9.2 11.5 13.8 16.1 18.4]


# NumPy - Indexing & Slicing

## Indexing

*This mechanism helps in selecting any arbitrary item in an array based on its Ndimensional index. Each integer array represents the number of indexes into that dimension. When the index consists of as many integer arrays as the dimensions of the target ndarray, it becomes straightforward.*

In [ ]:
x = np.array([[1, 2], [3, 4], [5, 6]])
print(x[1,1])

4


In [ ]:
x = np.array([[1, 2], [3, 4], [5, 6]])
y = x[[0,1,2], [0,1,0]]
print (y)

[1 4 5]


*The selection includes elements at (0,0), (1,1) and (2,0) from the first array.*

## Slicing

*A Python slice object is constructed by giving _start_, _stop_, and _step_ parameters to the built-in slice function. This slice object is passed to the array to extract a part of array.*

In [ ]:
a = np.arange(10)
s = slice(2,7,2)
print (a[s])

[2 4 6]


*The same result can also be obtained by giving the slicing parameters
separated by a colon : (start:stop:step) directly to the ndarray object.*

In [ ]:
# 1-D array
a = np.arange(10)
print(a[2:7:2])
print(a[2:])
print(a[2:5])

[2 4 6]
[2 3 4 5 6 7 8 9]
[2 3 4]


In [ ]:
#2-D array
a = np.array([[1,2,3],[3,4,5],[4,5,6]])
print(a)
print(a[1:])
print(a[1:,2])

[[1 2 3]
 [3 4 5]
 [4 5 6]]
[[3 4 5]
 [4 5 6]]
[5 6]


In [ ]:
#3-D array
x = np.arange(45).reshape(3,3,5)
print(x)
print(x[1:, 0])
print(x[1:, 0:2, 1:4])

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]

 [[30 31 32 33 34]
  [35 36 37 38 39]
  [40 41 42 43 44]]]
[[15 16 17 18 19]
 [30 31 32 33 34]]
[[[16 17 18]
  [21 22 23]]

 [[31 32 33]
  [36 37 38]]]


The notation and its results can seem confusing at first, so take your time to experiment and become comfortable with it. Use the cells below to try out some examples of array indexing and slicing, with different combinations of indices and ranges. Here are some more examples demonstrated visually:

<img src="https://scipy-lectures.org/_images/numpy_indexing.png" width="360">

##  NumPy - Arithmetic Operations

*Input arrays for performing arithmetic operations such as `add()`, `subtract()`, `multiply()`, and `divide()` must be either of the same shape or should conform to array broadcasting rules.*

In [ ]:
a = np.array([1,2,3])

print('First array:')
print(a)
print('Second array:')
b = np.array([4,5,6])
print(b)
print('Add the two arrays:')
print (np.add(a,b))
print('Subtract the two arrays:')
print(np.subtract(a,b))
print('Multiply the two arrays:')
print(np.multiply(a,b))
print('Divide the two arrays:')
print (np.divide(a,b))
print('Power function:')
print(np.power(a,b))

First array:
[1 2 3]
Second array:
[4 5 6]
Add the two arrays:
[5 7 9]
Subtract the two arrays:
[-3 -3 -3]
Multiply the two arrays:
[ 4 10 18]
Divide the two arrays:
[0.25 0.4  0.5 ]
Power function:
[  1  32 729]


In [ ]:
a = np.arange(9).reshape(3,3)

print('First array:')
print(a)
print('Second array:')
b = np.array([10,10,10])
print(b)
print('Add the two arrays:')
print (np.add(a,b))
print('Subtract the two arrays:')
print(np.subtract(a,b))
print('Multiply the two arrays:')
print(np.multiply(a,b))
print('Divide the two arrays:')
print (np.divide(a,b))
print('Power function:')
print(np.power(a,b))

First array:
[[0 1 2]
 [3 4 5]
 [6 7 8]]
Second array:
[10 10 10]
Add the two arrays:
[[10 11 12]
 [13 14 15]
 [16 17 18]]
Subtract the two arrays:
[[-10  -9  -8]
 [ -7  -6  -5]
 [ -4  -3  -2]]
Multiply the two arrays:
[[ 0 10 20]
 [30 40 50]
 [60 70 80]]
Divide the two arrays:
[[0.  0.1 0.2]
 [0.3 0.4 0.5]
 [0.6 0.7 0.8]]
Power function:
[[         0          1       1024]
 [     59049    1048576    9765625]
 [  60466176  282475249 1073741824]]


### Cumulative Sum

*`numpy.cumsum(a, axis=None, dtype=None, out=None)`*

_Returns cumulative sum along a given axis(successive additions)_

In [ ]:
e = np.arange(1,10).reshape(3,3)
print("Numpy array: ")
print(e)
print("Cumulative sum of flattened numpy array")
print(np.cumsum(e))
print("Cumulative sum along zeroth axis")
print(np.cumsum(e,axis = 0))
print("Cumulative sum along axis 1")
print(np.cumsum(e,axis = 1))
print("Cumulative sum along axis -2 which is same as the result of zeroth axis")
print(np.cumsum(e,axis = -2))

Numpy array: 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Cumulative sum of flattened numpy array
[ 1  3  6 10 15 21 28 36 45]
Cumulative sum along zeroth axis
[[ 1  2  3]
 [ 5  7  9]
 [12 15 18]]
Cumulative sum along axis 1
[[ 1  3  6]
 [ 4  9 15]
 [ 7 15 24]]
Cumulative sum along axis -2 which is same as the result of zeroth axis
[[ 1  2  3]
 [ 5  7  9]
 [12 15 18]]


### Difference

*`numpy.diff(a, n=1, axis=-1, prepend=<no value>, append=<no value>)`*
    
**Parameters**

|S.No|Parameter|Description|
|----|---------|-----------|
|1.|a|Input array|
|2.|n|Number of times values to be differenced||
|3.|axis|axis along which difference is taken|
|4.|prepend,append||

In [ ]:
a = np.array([1,4,5,3,6,7])
print("Numpy array")
print(a)
print("Differene after one time")
print(np.diff(a))
print("Difference after two times")
print(np.diff(a,n = 2))
print("Difference after three times")
print(np.diff(a,n = 3))
b = np.array([[1,4,2],
             [3,8,2],
             [5,9,10]])
print("Numpy array")
print(b)
print("One time difference between columns")
print(np.diff(b))
print("One time difference between rows")
print(np.diff(b,axis = 0))
print("Two time difference between rows")
print(np.diff(b,axis = 0,n = 2))
print("One time difference between columns")
print(np.diff(b,axis = 1))

Numpy array
[1 4 5 3 6 7]
Differene after one time
[ 3  1 -2  3  1]
Difference after two times
[-2 -3  5 -2]
Difference after three times
[-1  8 -7]
Numpy array
[[ 1  4  2]
 [ 3  8  2]
 [ 5  9 10]]
One time difference between columns
[[ 3 -2]
 [ 5 -6]
 [ 4  1]]
One time difference between rows
[[2 4 0]
 [2 1 8]]
Two time difference between rows
[[ 0 -3  8]]
One time difference between columns
[[ 3 -2]
 [ 5 -6]
 [ 4  1]]


## NumPy - Statistical Functions
NumPy has quite a few useful statistical functions for finding minimum, maximum, percentile standard deviation and variance, etc. from the given elements in the array.

### Order Statistics:
|Function|Description|
|--------|-----------|
|ptp(a[, axis, out,keepdims])|Range of values (maximum - minimum) along an axis|
|percentile(a, q[, axis, out, ...])|Compute the q-th percentile of the data along the specified axis|
|nanpercentile(a, q[, axis, out, ...])|Compute the qth percentile of the data along the specified axis, while ignoring nan values|
|quantile(a, q[, axis, out, overwrite_input, ...])|Compute the q-th quantile of the data along the specified axis|
|nanquantile(a, q[, axis, out, ...])|Compute the qth quantile of the data along the specified axis, while ignoring nan values|

###  Averages and variances:
|Function|Description|
|--------|-----------|
|median(a[, axis, out, overwrite_input, keepdims])|Compute the median along the specified axis|
|average(a[, axis, weights, returned, keepdims])|Compute the weighted average along the specified axis|
|mean(a[, axis, dtype, out, keepdims, where])|Compute the arithmetic mean along the specified axis|
|std(a[, axis, dtype, out, ddof, keepdims, where])|Compute the standard deviation along the specified axis|
|var(a[, axis, dtype, out, ddof, keepdims, where])|Compute the variance along the specified axis|
|nanmedian(a[, axis, out, overwrite_input, ...])|Compute the median along the specified axis, while ignoring NaNs|
|nanmean(a[, axis, dtype, out, keepdims, where])|Compute the arithmetic mean along the specified axis, ignoring NaNs|
|nanstd(a[, axis, dtype, out, ddof, ...])|Compute the standard deviation along the specified axis, while ignoring NaNs|
|nanvar(a[, axis, dtype, out, ddof, ...])|Compute the variance along the specified axis, while ignoring NaNs|

###  Correlating:
|Function|Description|
|--------|-----------|
|corrcoef(x[, y, rowvar, bias, ddof, dtype])|Return Pearson product-moment correlation coefficients|
|correlate(a, v[, mode])|Cross-correlation of two 1-dimensional sequences|
|cov(m[, y,rowvar,bias,ddof,fweights,...])|Estimate a covariance matrix, given data and weights|

## Matrix Transpose

*With the help of Numpy `matrix.transpose()` method, we can find the transpose of the matrix by using the `matrix.transpose()` method.*

In [ ]:
c = np.array([[1, 2, 3],
              [4, 5, 6],
              [7,8,9]])
print(c)
print("Transpose matrix is:")
print(c.transpose())

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Transpose matrix is:
[[1 4 7]
 [2 5 8]
 [3 6 9]]


*We can also find the transpose of the matrix by using the `matrix.T` method.*

In [ ]:
c = np.array([[1, 2, 3],
              [4, 5, 6],
              [7,8,9]])
print(c)
print("Transpose matrix is:")
print(c.T)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Transpose matrix is:
[[1 4 7]
 [2 5 8]
 [3 6 9]]


## Matrix Inverse

`numpy.matrix.I` returns the (multiplicative) inverse of invertible self.

__NOTE:__ First we have to convert the ndarray into matrix using `np.matrix(ndarray)`.
`matrix.getI()` returns the inverse of the given matrix.

In [ ]:
c = np.array([[1, 2],
              [3,4]])
print(c)
print("Inverse matrix is:")
m=np.matrix(c)
print(m.getI())

[[1 2]
 [3 4]]
Inverse matrix is:
[[-2.   1. ]
 [ 1.5 -0.5]]


## Matrix Multiplication

### numpy.matmul
*`numpy.matmul(x1, x2, /, out=None, *, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj, axes, axis]) = <ufunc 'matmul'>`*

_Matrix product of two arrays_

_Raises **ValueError** if last dimension of matrix1 is not same as first dimension of matrix2 or a scalar is passed_

In [ ]:
a = np.array([[1,2,3],
             [4,5,6],
             [7,8,9]])

b = np.array([[1],
             [2],
             [3]])

print(np.matmul(a,b))

[[14]
 [32]
 [50]]


<div class = "alert alert-block alert-info">
    <b>NOTE:</b> @ can also be used for matrix multiplication

In [ ]:
a @ b

array([[14],
       [32],
       [50]])

### numpy.dot

_Dot product of two arrays_

*`numpy.dot(a, b, out=None)`*

* If both a and b are 1-D arrays, it is inner product of vectors (without complex conjugation).


* If both a and b are 2-D arrays, it is matrix multiplication, but using matmul or a @ b is preferred.


* If either a or b is 0-D (scalar), it is equivalent to multiply and using numpy.multiply(a, b) or a * b is preferred.

## Lab Programs:-

#### 9. write a program to calculate the sum of every row in a numpy array.

In [ ]:
import numpy as np
m = int(input('rows : '))
n = int(input('columns : '))
arr = list(map(int,input('Enter array : ').split()))
arr = np.array(arr)
arr = np.resize(arr,(m,n))
print('array : ',arr)
list1 = []
for i in range(m):
    sum = np.sum(arr[i,:])
    list1.append(sum)
print('sum of rows : ',list1)

rows : 4
columns : 6
Enter array : 8
array :  [[8 8 8 8 8 8]
 [8 8 8 8 8 8]
 [8 8 8 8 8 8]
 [8 8 8 8 8 8]]
sum of rows :  [np.int64(48), np.int64(48), np.int64(48), np.int64(48)]


#### 10. write a python program to claculate the sum of every column in a numpy array.

In [ ]:
import numpy as np
m = int(input('rows : '))
n = int(input('columns : '))
arr = list(map(int,input('Enter array : ').split()))
arr = np.array(arr)
arr = np.resize(arr,(m,n))
print('array : ',arr)
list1 = []
for i in range(m):
    sum = np.sum(arr[:,i])
    list1.append(sum)
print('sum of columns : ',list1)

rows : 3
columns : 4
Enter array : 6
array :  [[6 6 6 6]
 [6 6 6 6]
 [6 6 6 6]]
sum of columns :  [np.int64(18), np.int64(18), np.int64(18)]


#### 11. write a numpy program to compute the 80 percentile for all elements in a given array along the second axis.

In [ ]:
import numpy as np
m = int(input('rows : '))
n = int(input('columns : '))
x = np.array(list(map(int,input().split()))).reshape((m, n))
print("\nArray:")
print(x)
r1 = np.percentile(x, 80, 1)
print("\n80th percentile for all elements of the said array along the second axis : ")
print(r1)

rows : 3
columns : 3
80% 70% 60% 50%


ValueError: invalid literal for int() with base 10: '80%'

In [ ]:
import numpy as np

m = int(input('rows : '))
n = int(input('columns : '))
x = np.array(list(map(int, input().split()))).reshape((m, n))

print("\nArray:")
print(x)

# Calculate 80th percentile along the second axis (axis=1)
r1 = np.percentile(x, 80, axis=1)
print("\n80th percentile for all elements of the said array along the second axis:")
print(r1)


rows : 3
columns : 3
80 60 70 80 90 80 70 80 90

Array:
[[80 60 70]
 [80 90 80]
 [70 80 90]]

80th percentile for all elements of the said array along the second axis:
[76. 86. 86.]


#### 12. write a numpy program to compute the median of flattned given array.

In [ ]:
import numpy as np
m = int(input('rows : '))
n = int(input('columns : '))
x = np.array(list(map(int,input().split()))).reshape((m, n))
print("\nOriginal array:")
print(x)
r1 =  np.median(x)
print("\nMedian of said array:")
print(r1)


rows : 3
columns : 3
80 90 70 70 80 90 90 80 70

Original array:
[[80 90 70]
 [70 80 90]
 [90 80 70]]

Median of said array:
80.0


#### 13. write a python program to compute the weighted of the given array.

In [ ]:
import numpy as np
x = np.array([0,1,2,3,4])
print("\nOriginal array:")
print(x)
weights = np.arange(1, 6)
r1 = np.average(x, weights=weights)
r2 = (x*(weights/weights.sum())).sum()
assert np.allclose(r1, r2)
print("\nWeighted average of the said array:")
print(r1)


Original array:
[0 1 2 3 4]

Weighted average of the said array:
2.6666666666666665


#### 14. Write a Numpy program to compute the covarience matrix of two given array.

In [ ]:
import numpy as np
array1 = np.array(list(map(int,input('array1 : ').split())))
array2 = np.array(list(map(int,input('array2 : ').split())))
print("\nOriginal array1:")
print(array1)
print("\nOriginal array1:")
print(array2)
print("\nCovariance matrix of the said arrays:\n",np.cov(array1, array2))

array1 : 2 4 6 8
array2 : 1 3 5 7 

Original array1:
[2 4 6 8]

Original array1:
[1 3 5 7]

Covariance matrix of the said arrays:
 [[6.66666667 6.66666667]
 [6.66666667 6.66666667]]


#### 15. write a NumPy program to compute cross-corelation of two given arrays.

In [ ]:
import numpy as np

array1 = np.array(list(map(float, input('array1 : ').split())))
array2 = np.array(list(map(float, input('array2 : ').split())))

print("\nOriginal array1:")
print(array1)

print("\nOriginal array2:")
print(array2)

print("\nCross-correlation of the said arrays:\n", np.correlate(array1, array2))


array1 : 1 2 3 
array2 : 0 1 0.5

Original array1:
[1. 2. 3.]

Original array2:
[0.  1.  0.5]

Cross-correlation of the said arrays:
 [3.5]


#### 16. write a python program to compute the weighted average along the specified axis of the given flattened array

In [ ]:
import numpy as np
m = int(input('rows : '))
n = int(input('columns : '))
a = np.array(list(map(float,input('array : ').split()))).reshape((m,n))
print("Original flattened array:")
print(a)
print("Weighted average along the specified axis of the above flattened array:")
print(np.average(a, axis=1, weights=[1./4, 2./4, 2./4]))

rows : 3
columns : 3
array : 9 8 7 6 5 4 3 2 1 
Original flattened array:
[[9. 8. 7.]
 [6. 5. 4.]
 [3. 2. 1.]]
Weighted average along the specified axis of the above flattened array:
[7.8 4.8 1.8]
